import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './custom.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

// sub sy main file or parent file
// boler plate only one
// all pages are children of layout file one main file
// frework are single page application 
// spa => single page application 
